import json
import os


CURRENT_PATH = os.getcwd()

FOXLINK_DATABASE_HOST = os.getenv("FOXLINK_DATABASE_HOST")
FOXLINK_DATABASE_PORT = os.getenv("FOXLINK_DATABASE_PORT")
FOXLINK_DATABASE_USER = os.getenv("FOXLINK_DATABASE_USER")
FOXLINK_DATABASE_PASSWORD = os.getenv("FOXLINK_DATABASE_PASSWORD")
FOXLINK_DATABASE_NAME = os.getenv("FOXLINK_DATABASE_NAME")

SERVER_URL = os.getenv("SERVER_URL")

MQTT_BROKER = os.getenv("MQTT_BROKER")
MQTT_PORT = int(os.getenv("MQTT_PORT"))

TESTING_LOG = bool(os.getenv("TESTING_LOG"))

RESPONSE_START = int(os.getenv("RESPONSE_START"))
RESPONSE_END = int(os.getenv("RESPONSE_END"))
REPAIR_START = int(os.getenv("REPAIR_START"))
REPAIR_END = int(os.getenv("REPAIR_END"))

SCENARIO = os.getenv("SCENARIO")